# Generated by Django 3.2.3 on 2021-06-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_answer',
        ),
    ]
